<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                                   => 'group_64648aa029bd9',
			'title'                                 => 'Branch Details',
			'fields'                                => array(
				array(
					'key'               => 'field_64648aa0f6a5f',
					'label'             => 'Address',
					'name'              => 'address',
					'type'              => 'google_map',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'center_lat'        => '',
					'center_lng'        => '',
					'zoom'              => '',
					'height'            => '',
				),
				array(
					'key'               => 'field_64648ab8f6a60',
					'label'             => 'Phone',
					'name'              => 'phone',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_64648abef6a61',
					'label'             => 'Opening Hours',
					'name'              => 'opening_hours',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'maxlength'         => '',
					'rows'              => '',
					'placeholder'       => '',
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_64648ac7f6a62',
					'label'             => 'Gallery',
					'name'              => 'gallery',
					'type'              => 'gallery',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'return_format'     => 'array',
					'library'           => 'all',
					'min'               => '',
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'insert'            => 'append',
					'preview_size'      => 'medium',
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'branch',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'normal',
			'style'                                 => 'default',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 1,
			'graphql_field_name'                    => 'branchDetails',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                                   => 'group_646489fd15db1',
			'title'                                 => 'Theme Options',
			'fields'                                => array(
				array(
					'key'               => 'field_646489fda4286',
					'label'             => 'Zoom Level',
					'name'              => 'zoom_level',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'min'               => 3,
					'max'               => 15,
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_64648a18a4287',
					'label'             => 'Language',
					'name'              => 'language',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'choices'           => array(
						'iw' => 'Hebrew',
						'en' => 'English',
						'ar' => 'Arabic',
						'ru' => 'Russian',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_64648a3ca4288',
					'label'             => 'Primary Color',
					'name'              => 'primary_color',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_64648a51a4289',
					'label'             => 'Text Color',
					'name'              => 'text_color',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_64648a59a428a',
					'label'             => 'Google Maps API Key',
					'name'              => 'google_maps_api_key',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_6467754f6d12b',
					'label'             => 'Enable Closing hours',
					'name'              => 'enable_closing_hours',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 0,
				),
				array(
					'key'               => 'field_6467756b6d12c',
					'label'             => 'From Hour',
					'name'              => 'from_hour',
					'type'              => 'time_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6467754f6d12b',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'display_format'    => 'H:i:s',
					'return_format'     => 'H:i:s',
				),
				array(
					'key'               => 'field_6467757e6d12d',
					'label'             => 'To Hour',
					'name'              => 'to_hour',
					'type'              => 'time_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6467754f6d12b',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'display_format'    => 'H:i:s',
					'return_format'     => 'H:i:s',
				),
				array(
					'key'               => 'field_646775b86d12e',
					'label'             => 'Closed Popup',
					'name'              => 'closed_popup',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6467754f6d12b',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_646775d06d12f',
							'label'             => 'Title',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 1,
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_646775d66d130',
							'label'             => 'Content',
							'name'              => 'content',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 1,
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'normal',
			'style'                                 => 'default',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 1,
			'graphql_field_name'                    => 'themeOptions',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	endif;
